### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by frogzhou** [freak07/OP7PRO#1]
On branch oneplus/SM8150_P_9.0_SDX
I edited nothing except the path of compiler, then I got following errors.

> ../net/wireguard/ratelimiter.c:185:33: warning: ordered comparison between
      pointer and integer ('unsigned long (*)(void)' and 'unsigned long')
        table_size = (totalram_pages() > (1U << 30) / PAGE_SIZE) ? 8192 :
                      ~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~
**../net/wireguard/ratelimiter.c:187:22: error: invalid operands to binary
      expression ('unsigned long (void)' and 'int')**
                        (totalram_pages() << PAGE_SHIFT) /
                         ~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~
../include/linux/log2.h:161:23: note: expanded from macro 'roundup_pow_of_two'
        __builtin_constant_p(n) ? (             \
                             ^
../include/linux/kernel.h:898:59: note: expanded from macro 'max_t'
#define max_t(type, x, y)       __careful_cmp((type)(x), (type)(y), >)
                                                                ^
../include/linux/kernel.h:822:38: note: expanded from macro '__careful_cmp'
        __builtin_choose_expr(__safe_cmp(x, y), \
                                            ^
../include/linux/kernel.h:812:19: note: expanded from macro '__safe_cmp'
                (__typecheck(x, y) && __no_side_effects(x, y))
                                ^
../include/linux/kernel.h:798:40: note: expanded from macro '__typecheck'
                (!!(sizeof((typeof(x) *)1 == (typeof(y) *)1)))
                                                     ^
../net/wireguard/ratelimiter.c:187:22: error: invalid operands to binary
      expression ('unsigned long (void)' and 'int')
                        (totalram_pages() << PAGE_SHIFT) /
                         ~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~
../include/linux/log2.h:162:4: note: expanded from macro 'roundup_pow_of_two'
                (n == 1) ? 1 :                  \
                 ^
../include/linux/kernel.h:898:59: note: expanded from macro 'max_t'
#define max_t(type, x, y)       __careful_cmp((type)(x), (type)(y), >)
                                                                ^
../include/linux/kernel.h:822:38: note: expanded from macro '__careful_cmp'
        __builtin_choose_expr(__safe_cmp(x, y), \
                                            ^
../include/linux/kernel.h:812:19: note: expanded from macro '__safe_cmp'
                (__typecheck(x, y) && __no_side_effects(x, y))
                                ^
../include/linux/kernel.h:798:40: note: expanded from macro '__typecheck'
                (!!(sizeof((typeof(x) *)1 == (typeof(y) *)1)))
                                                     ^
../net/wireguard/ratelimiter.c:187:22: error: invalid operands to binary
      expression ('unsigned long (void)' and 'int')
                        (totalram_pages() << PAGE_SHIFT) /
                         ~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~
../include/linux/log2.h:163:19: note: expanded from macro 'roundup_pow_of_two'
                (1UL << (ilog2((n) - 1) + 1))   \

How do I fix this?

clang: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/
aarch64-linux-android-4.9: https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/
arm-linux-androideabi-4.9: https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/

**Comment by kkuehl** [comment]
If you  use clang 9.05 or better,  it will compile.
mkdir -p ${HOME}/Downloads/clang
cd ${HOME}/Downloads/clang
git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86
cd ${HOME}/Downloads
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9
git clone https://github.com/freak07/OP7PRO.git
cd OP7PRO/
export PATH=${HOME}/Downloads/clang/linux-x86/clang-r365631/bin:${HOME}/Downloads/aarch64-linux-android-4.9/bin:$PATH
make ARCH=arm64 O=out kirisakura_defconfig
make -j$(nproc --all) O=out \
                      ARCH=arm64 \
                      CC=clang \
                      CLANG_TRIPLE=aarch64-linux-gnu- \
                      CROSS_COMPILE=aarch64-linux-android- \
                      CROSS_COMPILE_ARM32=arm-linux-androideabi-
ls -la out/arch/arm64/boot/
total 67408
drwxr-xr-x  3 user user     4096 Aug 23 15:53 .
drwxr-xr-x  9 user user     4096 Aug 23 15:45 ..
drwxr-xr-x 27 user user     4096 Aug 23 15:45 dts
-rw-r--r--  1 user user 42301456 Aug 23 15:53 Image
-rw-r--r--  1 user user      146 Aug 23 15:53 .Image.cmd
-rw-r--r--  1 user user 14314293 Aug 23 15:53 Image.gz
-rw-r--r--  1 user user      147 Aug 23 15:53 .Image.gz.cmd
-rw-r--r--  1 user user 16230461 Aug 23 15:53 Image.gz-dtb
-rw-r--r--  1 user user      297 Aug 23 15:53 .Image.gz-dtb.cmd

**Comment by frogzhou** [comment]
Thanks for your advice, but I have no luck.
It seems like that we cannot directly bit-shift the inlined function's return value. (totalram_pages())
So I add a local variable that hold the return value of inlined function mentioned above, it works well!

**Comment by LeCmnGend** [comment]
> Thanks for your advice, but I have no luck. It seems like that we cannot directly bit-shift the inlined function's return value. (totalram_pages()) So I add a local variable that hold the return value of inlined function mentioned above, it works well!

i have the same error here, do you remember how you fixed this.
